-- Generated by scripts/generate-workflow-vocabulary.mjs from skills/do/workflow-manifest.json. Do not edit.
module Agency.Scripts.Do.WorkflowVocabulary
  ( entryPoints
  , workflowSteps
  ) where

import Prelude

entryPoints :: Array String
entryPoints =
  [ "default"
  , "followup"
  , "post-implement"
  , "polish"
  , "ci-only"
  ]

workflowSteps :: Array String
workflowSteps =
  [ "sync"
  , "research"
  , "plan-approval"
  , "branch"
  , "implement"
  , "check"
  , "docs"
  , "fmt"
  , "commit"
  , "hickey-lowy"
  , "police"
  , "test"
  , "create-pr"
  , "ci"
  , "evidence"
  , "done"
  ]
