// Generated by scripts/generate-workflow-vocabulary.mjs from skills/do/workflow-manifest.json. Do not edit.
export const workflowEntryPoints = ["default","followup","post-implement","polish","ci-only"] as const;
