// Generated by scripts/generate-workflow-vocabulary.mjs from skills/do/workflow-manifest.json. Do not edit.
export const workflowEntryPoints = ["default","followup","post-implement","polish","ci-only"] as const;
export const workflowSteps = ["sync","research","plan-approval","branch","implement","check","docs","fmt","commit","hickey-lowy","police","test","create-pr","ci","evidence","done"] as const;
